image: maven:3.6.0-jdk-11

java:
  stage: test
  script:
  - mvn test -am
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml